import mi18n from 'mi18n'
import { isIE } from './common/helpers'

// eslint-disable-next-line no-undef
mi18n.addLanguage('pt-PT', {
  addOption: 'Adicionar Opção',
  allFieldsRemoved: 'Todos os campos foram removidos.',
  allowMultipleFiles: 'Permitir que os utilizadores enviem vários arquivos',
  autocomplete: 'Preencher Automaticamente',
  button: 'Botão',
  cannotBeEmpty: 'Este campo é de preenchimento obrigatório',
  checkbox: 'Caixa de seleção',
  checkboxes: 'Caixas de seleção',
  checkboxGroup: 'Grupo de seleção',
  className: 'Classe',
  clear: 'Limpar',
  clearAllMessage: 'Tem certeza que limpar todos os campos?',
  close: 'Fechar',
  content: 'Conteúdo',
  copy: 'Copiar',
  copyButton: '&#43;',
  copyButtonTooltip: 'Copiar',
  dateField: 'Campo de data',
  description: 'Descrição',
  descriptionField: 'Descrição',
  devMode: 'Modo programador',
  editNames: 'Editar nomes',
  editorTitle: 'Elementos do formulário',
  editXML: 'Editar XML',
  enableOther: 'Habilitar &quot;Outro&quot;',
  enableOtherMsg: 'Permitir que os utilizadores insiram uma nova opção',
  fieldDeleteWarning: 'Tem certeza que pretende apagar o campo?',
  fieldNonEditable: 'Este campo não pode ser editado.',
  fieldRemoveWarning: 'Tem certeza que deseja remover o campo?',
  fieldVars: 'Variáveis do campo',
  fileUpload: 'Envio de arquivo',
  formUpdated: 'Formulário atualizado',
  getStarted: 'Arraste campos aqui para começar',
  header: 'Cabeçalho',
  hidden: 'Campo oculto',
  hide: 'Ocultar',
  inline: 'Colocar em linha',
  inlineDesc: 'Mostrar {type} linear',
  label: 'Título',
  labelEmpty: 'Título do campo é de preenchimento obrigatório',
  limitRole: 'Permitir acesso apenas à:',
  mandatory: 'Obrigatório',
  maxlength: 'Tamanho máximo',
  minOptionMessage: 'Este campo exige no mínimo 2 opções',
  minSelectionRequired: 'Requer no mínimo {min} seleções',
  multipleFiles: 'Múltiplos arquivos',
  name: 'Nome',
  no: 'Não',
  noFieldsToClear: 'Não há campos para limpar',
  number: 'Número',
  off: 'Desativar',
  on: 'Ativar',
  option: 'Opção',
  optional: 'opcional',
  optionCount: 'Opção {count}',
  optionEmpty: 'Valor da opção é obrigatório',
  optionLabelPlaceholder: 'Título',
  options: 'Opções',
  optionValuePlaceholder: 'Valor',
  other: 'Outro',
  paragraph: 'Parágrafo',
  placeholder: 'Placeholder',
  'placeholders.className': 'classes separadas por espaco',
  'placeholders.email': 'E-mail',
  'placeholders.label': 'Título',
  'placeholders.password': 'Senha',
  'placeholders.placeholder': 'Placeholder',
  'placeholders.text': 'Texto',
  'placeholders.textarea': 'Texto',
  'placeholders.value': 'Valor',
  preview: 'Visualizar',
  radio: 'Opção',
  radioGroup: 'Grupo de opções',
  remove: '&#215;',
  removeMessage: 'Remover elemento',
  removeOption: 'Remover opção',
  required: 'Obrigatório',
  requireValidOption: 'Aceitar apenas opções pré-definidas',
  richText: 'Editor de texto',
  roles: 'Acesso',
  rows: 'Linhas',
  save: 'Salvar',
  select: 'Seleção',
  selectColor: 'Escolher cor',
  selectionsMessage: 'Permitir seleção múltipla',
  selectOptions: 'Opções',
  size: 'Tamanho',
  'size.lg': 'Largo',
  'size.m': 'Médio (padrão)',
  'size.sm': 'Pequeno',
  'size.xs': 'Extra pequeno',
  style: 'Estilo',
  'styles.btn.danger': 'Perigo',
  'styles.btn.default': 'Padrão',
  'styles.btn.info': 'Informação',
  'styles.btn.primary': 'Primário',
  'styles.btn.success': 'Sucesso',
  'styles.btn.warning': 'Aviso',
  subtype: 'Tipo',
  text: 'Campo de texto',
  textArea: 'Área de texto',
  toggle: 'Alternar',
  value: 'Valor',
  viewJSON: '[{&hellip;}]',
  viewXML: '&lt;/&gt;',
  warning: 'Aviso!',
  yes: 'Sim',
})

export const defaults = {
  get editor() {
    return {
      stickyControls: false,
      allowEdit: true,
      dataType: 'json',
      debug: false,
      sessionStorage: false,
      editorContainer: null, // element or selector to attach editor to
      external: {}, // assign external data to be used in conditions autolinker
      svgSprite: null, // change to null
      iconFont: null, // 'glyphicons' || 'font-awesome' || 'fontello'
      config: {}, // stages, rows, columns, fields
      events: {},
      actions: {},
      controls: {},
      polyfills: isIE(), // loads csspreloadrel
      i18n: {
        // extension: '.lang',
        // location: './i18n/',
        locale: 'pt-PT'
      },
    }
  },
}
